import { initializeApp } from 'https://www.gstatic.com/firebasejs/12.18.0/firebase-app.js';
import { getAuth, onAuthStateChanged, signOut } from 'https://www.gstatic.com/firebasejs/12.18.0/firebase-auth.js';
import { getFirestore, collection, getDocs, getDoc, doc, query, where, orderBy, limit, addDoc, setDoc, updateDoc, deleteDoc, serverTimestamp } from 'https://www.gstatic.com/firebasejs/12.18.0/firebase-firestore.js';
import { firebaseConfig } from '../firebase/config.js';

export const firebaseApp=initializeApp(firebaseConfig); export const auth=getAuth(firebaseApp); export const db=getFirestore(firebaseApp);
export const money=n=>`PKR ${Number(n||0).toLocaleString('en-PK',{maximumFractionDigits:2})}`;
export const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
export const icon=(name,size=20)=>{const paths={cart:'<path d="M6 6h15l-1.5 9h-12z"/><path d="M6 6 5 3H2"/><circle cx="9" cy="20" r="1"/><circle cx="18" cy="20" r="1"/>',user:'<path d="M20 21a8 8 0 0 0-16 0"/><circle cx="12" cy="7" r="4"/>',menu:'<path d="M4 6h16M4 12h16M4 18h16"/>',search:'<circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/>',plus:'<path d="M12 5v14M5 12h14"/>',minus:'<path d="M5 12h14"/>',arrow:'<path d="M5 12h14M13 6l6 6-6 6"/>',check:'<path d="m5 12 4 4L19 6"/>',x:'<path d="m6 6 12 12M18 6 6 18"/>',milk:'<path d="M7 3h10l2 4v14H5V7z"/><path d="M7 7h12M8 11h8M8 15h6"/>',box:'<path d="m3 7 9-4 9 4-9 4z"/><path d="M3 7v10l9 4 9-4V7M12 11v10"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',location:'<path d="M20 10c0 5-8 11-8 11S4 15 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2"/>'};return `<svg width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[name]||paths.box}</svg>`};
export function getCart(){try{return JSON.parse(localStorage.getItem('rohan_cart')||'[]')}catch{return[]}} export function setCart(c){localStorage.setItem('rohan_cart',JSON.stringify(c));updateCartCount()}
export function addToCart(product,quantity=1){const cart=getCart(); const i=cart.findIndex(x=>x.id===product.id); if(i>=0)cart[i].quantity=Number(cart[i].quantity)+Number(quantity); else cart.push({id:product.id,name:product.name,price:Number(product.price),unit:product.unit||'unit',quantity:Number(quantity),stock:Number(product.stock??999999),image:product.image||''}); setCart(cart); toast(`${product.name} added to cart`)}
export function removeFromCart(id){setCart(getCart().filter(x=>x.id!==id))} export function updateCartItem(id,q){const c=getCart();const i=c.findIndex(x=>x.id===id);if(i<0)return; c[i].quantity=Math.max(0,Number(q)); if(!c[i].quantity)c.splice(i,1);setCart(c)}
export function cartTotals(){const items=getCart();const subtotal=items.reduce((s,x)=>s+Number(x.price)*Number(x.quantity),0);return {subtotal,total:subtotal,count:items.reduce((s,x)=>s+Number(x.quantity),0)}}
export function toast(msg){let t=document.querySelector('.toast');if(!t){t=document.createElement('div');t.className='toast';document.body.appendChild(t)}t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
export function track(event,params={}){window.dataLayer=window.dataLayer||[];window.dataLayer.push({event,...params})}
export async function getProducts(category='all'){let q=collection(db,'products'); if(category&&category!=='all')q=query(q,where('category','==',category)); const snap=await getDocs(q); return snap.docs.map(d=>({id:d.id,...d.data()}))}
export async function getProduct(id){const s=await getDoc(doc(db,'products',id));return s.exists()?{id:s.id,...s.data()}:null}
export async function getSettings(){const s=await getDoc(doc(db,'settings','store'));return s.exists()?s.data():{storeName:'Rohan Milk Shop',location:'Pakistan — Temporary Store Location',hours:'8:00 AM – 10:00 PM (Temporary)',phone:'+92 300 0000000',whatsapp:'+92 300 0000000',payments:['cash_pickup','bank_transfer','easypaisa','jazzcash']}}
export function renderHeader(){const root=document.querySelector('#site-header');if(!root)return;root.innerHTML=`<div class="topbar"><div class="container"><span>Fresh dairy products • Store pickup only</span><span>Pakistan · Temporary location</span></div></div><header class="site-header"><div class="container nav"><button class="icon-btn mobile-menu" id="menuBtn" aria-label="Open menu">${icon('menu')}</button><a class="logo" href="index.html"><img src="assets/rohan-logo.png" alt="Rohan Milk Shop logo"></a><nav class="nav-links" aria-label="Primary"><a href="index.html">Home</a><a href="shop.html">Shop</a><a href="shop.html?category=Milk">Fresh Milk</a><a href="shop.html?category=Dairy">Dairy</a><a href="account.html">My Orders</a></nav><div class="nav-actions"><a class="icon-btn account-link" href="auth.html" aria-label="Account">${icon('user')}</a><a class="icon-btn" href="cart.html" aria-label="Cart">${icon('cart')}<span class="badge-count" id="cartCount">0</span></a></div></div></header><div id="mobileNav" class="hide" style="background:#fff;border-bottom:1px solid var(--color-border)"><div class="container" style="padding:10px 0;display:grid;gap:4px"><a class="btn btn-secondary" href="index.html">Home</a><a class="btn btn-secondary" href="shop.html">Shop</a><a class="btn btn-secondary" href="account.html">My Orders</a></div></div>`;document.querySelector('#menuBtn')?.addEventListener('click',()=>document.querySelector('#mobileNav').classList.toggle('hide'));updateCartCount();}
export function renderFooter(){const f=document.querySelector('#site-footer');if(!f)return;f.innerHTML=`<footer class="footer"><div class="container footer-grid"><div><img src="assets/rohan-logo.png" alt="Rohan Milk Shop" style="width:150px;background:#fff;border-radius:8px;padding:4px"><p>Fresh dairy essentials made simple. Order online and collect your order from our shop.</p></div><div><h3>Shop</h3><p><a href="shop.html">All Products</a></p><p><a href="shop.html?category=Milk">Fresh Milk</a></p><p><a href="shop.html?category=Dairy">Dairy Products</a></p></div><div><h3>Pickup</h3><p>Pakistan — temporary location</p><p>8:00 AM – 10:00 PM — temporary hours</p><p>+92 300 0000000 — temporary</p></div></div><div class="container footer-bottom"><span>© ${new Date().getFullYear()} Rohan Milk Shop</span><span>Store pickup only · PKR</span></div></footer>`}
export function updateCartCount(){const e=document.querySelector('#cartCount');if(e)e.textContent=cartTotals().count}
export function setupAuthUI(){onAuthStateChanged(auth,user=>{document.querySelectorAll('[data-auth-user]').forEach(e=>e.textContent=user?.displayName||user?.email||'Guest')});}
export {collection,getDocs,getDoc,doc,query,where,orderBy,limit,addDoc,setDoc,updateDoc,deleteDoc,serverTimestamp,onAuthStateChanged,signOut};
